theme: jekyll-theme-minimal

# Short description (goes below the title; it will also be used in the RSS feed)
description: Personal site and blog. Please feel free to contact me via the social networks below.

# Google Analytics
google_analytics: UA-132342938-1
